import { Box, Sheet } from '@mui/joy'
import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cuisine-connect',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <nav><Header /></nav>
        <main>
          <Box
            sx={{
              bgcolor: 'white',
              // display: 'grid',
              gridTemplateRows: '52px 0px 1fr',
              minHeight: '110dvh',
            }}
          >
            <Sheet>
              {children}
            </Sheet>
          </Box>
        </main>
      </body>
    </html>
  )
}
