version: "3"

services:
  nodejs:
    image: node:alpine
    container_name: cuisine-connect-nodejs
    working_dir: /home/app/cuisine-connect
    tty: true
    stdin_open: true
    user: node
    env_file:
      - .env.local
    volumes:
      - ./:/home/app
    ports:
      - 3000:3000
    networks:
      - dev
  db:
    image: postgres:14.2
    container_name: cuisine-connect-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - 5433:5432
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - dev

  adminer:
    image: adminer:4.8.1
    container_name: cuisine-connect-adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: nette
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
